name: DiscordChat
main: me.petterim1.discordchat.Loader
version: "${pom.version}"
api: ["1.0.0"]
author: PetteriM1
description: Sync Discord chat with your Nukkit server
website: https://cloudburstmc.org/resources/discordchat.137/
commands:
  discord:
    description: "Discord"
    usage: "/discord [mute|unmute|reload]"
    permission: discordchat.command
  linkdiscord:
    description: "Get a verification code to link your Discord Account!"
    usage: "/linkdiscord"
    permission: discordchat.command
  unlinkdiscord:
    description: "Admin| Unlink a players discord ID from his account!"
    usage: "/unlinkdiscord <playername>"
    permission: discordchat.admin
permissions:
  discordchat.command:
    default: true
  discordchat.admin:
    default: op
